name: Maryville Boxing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c71c16'
    - '#010000'
    - '#555555'
    - '#bab9b9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
